name: Geologic Processing API

on:
  workflow_dispatch:
    inputs:
      coordinates:
        description: 'Coordinates in format "NW_LAT,NW_LON,SE_LAT,SE_LON"'
        required: true
        default: '10.0,-5.0,9.0,-4.0'
      parameters:
        description: 'Processing parameters as JSON string'
        required: false
        default: '{}'

jobs:
  process-area:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      CDSE_USERNAME: ${{ secrets.CDSE_USERNAME }}
      CDSE_PASSWORD: ${{ secrets.CDSE_PASSWORD }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask==2.3.3 flask-cors==4.0.0 numpy==1.24.3 scipy==1.10.1 matplotlib==3.7.2 Pillow==10.0.0 requests==2.31.0 sentinelsat==1.1.1 rasterio==1.3.8 shapely==2.0.1 geopandas==0.13.2

    - name: Run processing
      run: |
        python main.py process --coordinates "${{ github.event.inputs.coordinates }}" --parameters '${{ github.event.inputs.parameters }}'
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: processing-results
        path: |
          outputs/*
        retention-days: 7

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: processing-logs
        path: |
          processing.log
        retention-days: 7
