name: Geologic Processing API

on:
  workflow_dispatch:
    inputs:
      coordinates:
        description: 'Coordinates in format "NW_LAT,NW_LON,SE_LAT,SE_LON"'
        required: true
        default: '10.0,-5.0,9.0,-4.0'
      parameters:
        description: 'Processing parameters as JSON string'
        required: false
        default: '{}'

jobs:
  process-area:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask==2.3.3 flask-cors==4.0.0 numpy==1.24.3 scipy==1.10.1 matplotlib==3.7.2 Pillow==10.0.0 requests==2.31.0

    - name: Run processing
      env:
        CDSE_USERNAME: ${{ secrets.CDSE_USERNAME }}
        CDSE_PASSWORD: ${{ secrets.CDSE_PASSWORD }}
        COORDINATES: ${{ github.event.inputs.coordinates }}
        PARAMETERS: ${{ github.event.inputs.parameters }}
      run: |
        cd app
        python main.py process --coordinates "$COORDINATES" --parameters '$PARAMETERS'
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: processing-results
        path: |
          app/outputs/*
        retention-days: 7
