name: Geologic Processing API

on:
  workflow_dispatch:  # Manual trigger
  repository_dispatch:  # Allow external triggers via API

jobs:
  run-app:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask==2.3.3 flask-cors==4.0.0 numpy==1.24.3 scipy==1.10.1 matplotlib==3.7.2 Pillow==10.0.0 requests==2.31.0

    - name: Run Python app
      run: |
        # Start the server in background
        python github_app.py &
        
        # Wait for server to start
        sleep 10
        
        # Test the server with a simple request
        curl -X POST http://localhost:8080/process \
          -H "Content-Type: application/json" \
          -d '{"coordinates": "10,10,9,9"}' \
          --connect-timeout 30 \
          --max-time 60
        
        # Keep the action running
        sleep 300
